<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.3.2 setup script
 * Date: Fri, 12 Aug 2011 15:29:42 -0700
 */

/* Servers configuration */
$i = 0;

/* Server: mysql.ocf.berkeley.edu [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'mysql.ocf.berkeley.edu';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'amsa';
$cfg['Servers'][$i]['password'] = 'V5vpeAsNVge3e83f7TBP';
$cfg['Servers'][$i]['ssl'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '4e459f1fd52a18.69897827';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = true;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>